# Generated by Django 3.2.25 on 2024-03-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0001_initial'),
    ]

    operations = [
    ]
